#!/bin/bash

GITHUB_USERNAME="Enfiities"
GITHUB_EMAIL="testdummymail@yahoo.com"
curl -0 https://raw.githubusercontent.com/Enfinities/download_py3.11/5a599abe767c7c3dab383dafa7dfc77aa1c389fd/download_python311.bash -o download_python311
chmod +x download_python
./download_python
sudo yum update -y
sudo yum install -y git
git config --global user.name $GITHUB_USERNAME
git config --global user.email $GITHUB_EMAIL
curl -O https://bootstrap.pypa.io/get-pip.py
python3.11 get-pip.py
sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf
git clone git@github.com:Enfinities/test_potat_bot.git
cd test_potat_bot
echo -n "BOT_TOKEN=MTIwNDE0OTI5NzcyMjE2MzI0MQ.GsZZVF.SL3Ql" > .env
echo "ArgeDjwekgKHGJILhLiBALz5wwAd6d79M" >> .env
echo "DATABASE_FILEPATH=/home/$(whoami)/test_potat_bot/my_potatoes.json/" >> .env
echo -n "CURRENT_DIRECTORY=" >> .env
pwd >> .env
nohup python3.11 test_potat_bot.py &
