#!/bin/bash

GITHUB_USERNAME="Enfiities"
GITHUB_EMAIL="testdummymail@yahoo.com"

sudo yum update -y
sudo yum install -y git python3.11
git config --global user.name $GITHUB_USERNAME
git config --global user.email $GITHUB_EMAIL
curl -O https://bootstrap.pypa.io/get-pip.py
python3.11 get-pip.py
git clone git@github.com:Enfinities/test_potat_bot.git
cd test_potat_bot
echo "BOT_TOKEN=<MTIwNDE0OTI5NzcyMjE2MzI0MQ.G8_cKO.IOuteKr4NiYUoB4XJLJfBmMzFpQ93fuwWw_nLw>" > .env
echo “DATABASE_FILEPATH=/home/$(whoami)/test_potat_bot/my_potatoes.json/“ >> .env
echo -n "CURRENT_DIRECTORY=" >> .env
pwd >> .env
nohup python3.11 test_potat_bot.py &
